### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by slabys** [slabys/mois#57]
BE:
- [x] FIX images
- [x] User application - Separate past event / upcoming Event
- [x] Generate PDF
- [x] Download PDF (or show on server via URL)
- [x] Poslat adresu userovi
- [x] Role
- [x] Event image add (png, jpeg allowed)
- [x] Delete eventu
- [x] poslat capacity na getEvents
- [x] výpis všech uživatelů
- [x] `/events/${eventId}/applications`- nevrací invoice address tý application
- [x] `/events/spots/{id}` - replaceWithSpotId může být null
- [x] EP - fetch organization by ID
- [x] EP - Get All Users (/users/all) - přidat detail výpisu user (do které organizace patří)
- [x] Paginace na EP vrací pouze pole všech záznamů, nevrací max počet záznamů - Potřeba vrátit počet možných stránek 

FE:
- [x] User application - Separate past event / Upcoming Event 
- [x] Duplicate Event
- [x] Dodělat Event Applications - Delete (partialy done) / Update sent application 
- [x] Role
- [ ] ~Invoices~
- [ ] ~Delete event~
- [x] refetch při vytvoření spotu
- [x] Výpis organizací
- [x] Přidání usera do organizace
- [x] odstranění usera z organizace
- [x] update organizace
- [x] vytvoření organizace

Testing chyby
- [x] event spot delete
- [x] spot type change špatný název notifikace
- [ ] generate invoice v manage applications nic nedělá
- [ ] Manage organisations member edit tlačítko nic nedělá
- [x] Create organization nic nedělá
